version: 2
jobs:
  build:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: unit tests
          command: nimble test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
